steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_IMG'
      - '--build-arg'
      - 'REACT_APP_GOOGLE_CLIENT_ID=${_REACT_APP_GOOGLE_CLIENT_ID}'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_API_KEY=${_REACT_APP_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_AUTH_DOMAIN=${_REACT_APP_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_PROJECT_ID=${_REACT_APP_FIREBASE_PROJECT_ID}'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_STORAGE_BUCKET=${_REACT_APP_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - 'REACT_APP_MESSAGING_SENDER_ID=${_REACT_APP_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_APP_ID=${_REACT_APP_FIREBASE_APP_ID}'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_MEASUREMENT_ID=${_REACT_APP_FIREBASE_MEASUREMENT_ID}'
      - '--build-arg'
      - 'BACKEND_URL=${_BACKEND_URL}'
      - '--build-arg'
      - 'ANALYSIS_API=${_ANALYSIS_API}'
      - '.'
images:
  - '$_IMG'
