FROM node:18-slim

WORKDIR /app

# ติดตั้ง deps แบบ production
COPY package*.json ./
RUN npm ci --omit=dev

# คัดซอร์ส
COPY . .

ENV NODE_ENV=production
ENV PORT=5000

EXPOSE 5000
CMD ["npm","start"]
